var typed = new Typed(".auto-type", {
    strings: [ 
        'hello',
        'hi',
        'hey',
        "g'day",
        'bonjour',
        'yo',
        'hola',
        'hej',
        'morning!',
        'hallo',
        'ciao',
        'namaste',
        'hoi',
        'hiya',
        'Привет',
        'مرحبا',
        'aloha',
        'こんにちは',
        'buenos dias',
        'nuqneH',
        'heya',
        'olà',
        'apipoulaï',
        'j0',
        'howdy',
        'שלום',
        '你好',
        '在吗？',
        'fraeslis',
        '여보세요',
        'sul sul',
        'achuta',
        'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
        'Χαίρετε',
        'سلام',
    ],
    typeSpeed: 150,
    backSpeed: 150,
    loop: true
})